### ISSUE TITLE
can't install frei0r-9999

### ISSUE THREAD

**Issue by RayOfLight1** [istitov/stuff#109]
My merge fails on the install phase with:

```

Traceback (most recent call last):
  File "/usr/lib/portage/python3.6/doins.py", line 611, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/lib/portage/python3.6/doins.py", line 602, in main
    os.path.dirname(source)):
  File "/usr/lib/portage/python3.6/doins.py", line 450, in _doins
    return install_runner.install_file(source, os.path.dirname(dest))
  File "/usr/lib/portage/python3.6/doins.py", line 386, in install_file
    return self._ins_runner.run(source, dest_dir)
  File "/usr/lib/portage/python3.6/doins.py", line 195, in run
    sstat = os.stat(source)
FileNotFoundError: [Errno 2] No such file or directory: b'README'
 * ERROR: media-plugins/frei0r-plugins-9999::stuff failed (install phase):
 *   dodoc failed

```

Please advice.

**Comment by alexws54tk** [comment]
Sync repo and please remerge.

**Comment by istitov** [comment]
#135
